;(function (g) {
	const PROTOCOL_TYPES = {
		GET_CONFIG: 'NC_GET_CONFIG',
		SAVE_CONFIG: 'NC_SAVE_CONFIG',
		START_TASK: 'NC_START_TASK',
		STOP_TASK: 'NC_STOP_TASK',
		CONFIRM_RESPONSE: 'NC_CONFIRM_RESPONSE',
		ASK_USER_REQUEST: 'NC_ASK_USER_REQUEST',
		OBSERVE: 'NC_OBSERVE',
		ACT: 'NC_ACT',
		ACT_COORD: 'NC_ACT_COORD',
		HIT_TEST: 'NC_HIT_TEST',
		SET_VISUAL_CAPTURE_MODE: 'NC_SET_VISUAL_CAPTURE_MODE',
		VERIFY_INPUT: 'NC_VERIFY_INPUT',
		VERIFY_INPUT_POINT: 'NC_VERIFY_INPUT_POINT',
		CONFIRM_REQUEST: 'NC_CONFIRM_REQUEST',
		SESSION_UPDATE: 'NC_SESSION_UPDATE',
	}

	const STATUS = {
		IDLE: 'idle',
		RUNNING: 'running',
		COMPLETED: 'completed',
		ERROR: 'error',
		STOPPED: 'stopped',
	}

	g.NC_PROTOCOL = {
		TYPES: PROTOCOL_TYPES,
		STATUS,
	}
})(globalThis)
